name: Node.js CI, Load Testing & SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Pruebas Unitarias y de Integración con Jest
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.20.0, 18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test

  # Job 2: Pruebas de Carga con K6
  load-test:
    needs: test # Solo se ejecuta si el Job "test" es exitoso
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.20.0
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      # Levantamos el servidor en segundo plano apuntando al script correcto
      - name: Start the Express application
        run: node ./bin/www & 
        
      - name: Wait for server to be ready
        run: sleep 5
        
      # Instalamos K6 de forma nativa
      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      # Ejecutamos la prueba de K6 y enviamos resultados a Grafana Cloud
      - name: Run K6 load test and stream to Grafana Cloud
        run: k6 run k6-test.js --out cloud
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}

  # Job 3: Análisis de Calidad de Código con SonarQube (Nuevo)
  sonarQube-analysis:
    name: Análisis SAST
    runs-on: ubuntu-latest
    steps:
      - name: Clonación del repositorio (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Requerido por SonarQube para un análisis histórico completo
          
      - name: Ejecución de Escáner SonarQube
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=node-proyect
            -Dsonar.qualitygate.wait=true
